# server.port = 8181 #properties

server:
  port: 8181

#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.pasword=

#spring:
#  datasource:
#    url: xxx
#    username: xxx
#    password: xxx
#
